### ISSUE TITLE
Method not found when @Id is used with UUID type

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean#1219]
## Ebean version

11.6.1

Everything works with the version 11.4.1

## Expected behavior
Retrieve or save object into database

## Actual behavior
The JVM shutdown with an Ebean error message

### Steps to reproduce

```java
  @Id
  @Column(name = "id")
  public java.util.UUID id
```

```console
  ncaught error from thread [application-akka.actor.default-dispatcher-24]: io.ebean.bean.EntityBeanIntercept.preSetter(ZILjava/lang/Object;Ljava/lang/Object;)Ljava/beans/PropertyChangeEvent;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[application]
java.lang.NoSuchMethodError: io.ebean.bean.EntityBeanIntercept.preSetter(ZILjava/lang/Object;Ljava/lang/Object;)Ljava/beans/PropertyChangeEvent;
	at com.zero_x_baadf00d.play.module.aws.s3.ebean.BaseS3FileModel._ebean_set_id(BaseS3FileModel.java:1)
	at com.zero_x_baadf00d.play.module.aws.s3.ebean.S3FileModel._ebean_setFieldIntercept(S3FileModel.java:1)
	at io.ebeaninternal.server.properties.EnhanceBeanPropertyAccess$Setter.setIntercept(EnhanceBeanPropertyAccess.java:84)
	at io.ebeaninternal.server.deploy.BeanProperty.setValueIntercept(BeanProperty.java:734)
	at io.ebeaninternal.server.deploy.id.IdBinderSimple.convertSetId(IdBinderSimple.java:261)
	at io.ebeaninternal.server.deploy.BeanDescriptor.convertSetId(BeanDescriptor.java:2086)
	at io.ebeaninternal.server.deploy.BeanDescriptor.createReference(BeanDescriptor.java:1797)
	at io.ebeaninternal.server.deploy.BeanDescriptor.contextRef(BeanDescriptor.java:1991)
	at io.ebeaninternal.server.deploy.AssocOneHelp.read(AssocOneHelp.java:49)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.read(BeanPropertyAssocOne.java:600)
	at io.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:74)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.load(BeanPropertyAssocOne.java:642)
	at io.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:293)
	at io.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:443)
	at io.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:531)
	at io.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:562)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:367)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:149)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:405)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1531)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1243)
	at io.ebeaninternal.server.expression.DefaultExpressionList.findList(DefaultExpressionList.java:395)
	at controllers.AllDirectives.resolveStations(AllDirectives.java:121)
```

**Comment by rbygrave** [comment]
You need to use the new agent for enhancement.  Upgrade your agent and try again.

**Comment by 0xbaadf00d** [comment]
Thank you Rob. It working.
